title: Voice Transcriber
type: community
group: Voice Analytics
order: 1
image: /static/templates/Transcriber.png
details: <h1>Provide transcript for the audio</h1>
config: |
  <View>
    <Audio name="audio" value="$audio" zoom="true" hotkey="ctrl+enter" />
    <Header value="Provide Transcription" />
    <TextArea name="transcription" toName="audio"
              rows="4" editable="true" maxSubmissions="1" />
  </View>

